dist: precise

language: php

php:
  - '5.3'
  - '5.4'
  - '5.5'  
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4'

env:
  - TESTER_PHP_BIN="php"

before_install:
  - composer self-update

install:
  - composer install --no-interaction --prefer-source  

script:
  - ./vendor/bin/tester -p $TESTER_PHP_BIN -s ./tests/src

after_failure:
  - for i in $(find ./tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done  
